export const leaderboard = [
    {"user_id": 111, "username": "morgan.rodriguez21", "full_name": "Morgan Rodriguez", "rank": 1, "score": 25795, "profile_pic": "profile9.png"},
    {"user_id": 455, "username": "blake.young82", "full_name": "Blake Young", "rank": 2, "score": 21093, "profile_pic": "profile8.png"},
    {"user_id": 247, "username": "nova.brooks97", "full_name": "Nova Brooks", "rank": 3, "score": 24571, "profile_pic": "profile16.png"},
    {"user_id": 524, "username": "gray.bennett65", "full_name": "Gray Bennett", "rank": 4, "score": 19297, "profile_pic": "profile16.png"},
    {"user_id": 529, "username": "logan.garcia71", "full_name": "Logan Garcia", "rank": 5, "score": 19861, "profile_pic": "profile12.png"},
    {"user_id": 111, "username": "drew.young52", "full_name": "Drew Young", "rank": 6, "score": 21745, "profile_pic": "profile14.png"},
    {"user_id": 1076, "username": "indigo.harris15", "full_name": "Indigo Harris", "rank": 7, "score": 23583, "profile_pic": "profile3.png"},
    {"user_id": 308, "username": "indigo.king5", "full_name": "Indigo King", "rank": 8, "score": 23280, "profile_pic": "profile9.png"},
    {"user_id": 625, "username": "parker.harris49", "full_name": "Parker Harris", "rank": 9, "score": 23227, "profile_pic": "profile11.png"},
    {"user_id": 653, "username": "morgan.garcia25", "full_name": "Morgan Garcia", "rank": 10, "score": 22534, "profile_pic": "profile4.png"},
    {"user_id": 158, "username": "sage.brown39", "full_name": "Sage Brown", "rank": 11, "score": 26949, "profile_pic": "profile16.png"},
    {"user_id": 931, "username": "harper.brooks84", "full_name": "Harper Brooks", "rank": 12, "score": 28304, "profile_pic": "profile13.png"},
    {"user_id": 939, "username": "kai.smith69", "full_name": "Kai Smith", "rank": 13, "score": 19114, "profile_pic": "profile7.png"},
    {"user_id": 965, "username": "indigo.harris58", "full_name": "Indigo Harris", "rank": 14, "score": 19450, "profile_pic": "profile10.png"},
    {"user_id": 310, "username": "nova.martinez56", "full_name": "Nova Martinez", "rank": 15, "score": 26963, "profile_pic": "profile15.png"},
    {"user_id": 444, "username": "morgan.walker67", "full_name": "Morgan Walker", "rank": 16, "score": 26256, "profile_pic": "profile15.png"},
    {"user_id": 387, "username": "indigo.cook8", "full_name": "Indigo Cook", "rank": 17, "score": 21737, "profile_pic": "profile13.png"},
    {"user_id": 751, "username": "riley.torres16", "full_name": "Riley Torres", "rank": 18, "score": 18554, "profile_pic": "profile3.png"},
    {"user_id": 483, "username": "logan.johnson35", "full_name": "Logan Johnson", "rank": 19, "score": 27911, "profile_pic": "profile6.png"},
    {"user_id": 411, "username": "harper.bennett42", "full_name": "Harper Bennett", "rank": 20, "score": 22946, "profile_pic": "profile14.png"}
]
